# Generated by Django 5.1.4 on 2024-12-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0004_alter_post_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.IntegerField(max_length=4)),
            ],
        ),
    ]
