# Generated by Django 5.1.4 on 2024-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
