# Generated by Django 5.1.4 on 2024-12-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0005_broj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broj',
            name='broj',
            field=models.IntegerField(),
        ),
    ]
