# Generated by Django 5.1.4 on 2024-12-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0006_alter_broj_broj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Broj',
            new_name='Number',
        ),
    ]
